version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-api:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:newsapi_secure_password@db:5432/newsapi
      - API_KEY=dev_api_key
      - DEBUG=true
      - ENABLE_BACKGROUND_COLLECTION=true
      - ENABLE_ML_CLASSIFICATION=true
      - ENABLE_GDELT=true
      # Google Cloud configuration
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json
      - GOOGLE_CLOUD_PROJECT=news-aggr-api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./gcp-key.json:/app/gcp-key.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=newsapi_secure_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=newsapi
    ports:
      - "5433:5432"
    volumes:
      - newsapi_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newsapi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  newsapi_postgres_data:
    driver: local