version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/newsapi
      - API_KEY=dev_api_key
      - DEBUG=true
    depends_on:
      - db
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=newsapi
    ports:
      - "5433:5432"  # Changed from 5432:5432 to use port 5433 externally

volumes:
  postgres_data: